"""
OpportunityOS — Outcome Analytics Engine
========================================
Authorized by: Sprint 2.1 (approved implementation_plan.md)

Responsibilities:
    - Query opportunity_feedback and opportunities tables to construct metrics
    - Generate structured markdown reports showing top performing dimensions
    - Output report to memory directory for learning and model tuning
"""

import logging
from typing import Any
from db import client as db_client

logger = logging.getLogger(__name__)

def get_outcomes_by_source() -> list[dict[str, Any]]:
    query = """
    SELECT 
        o.source,
        COUNT(*) FILTER (WHERE f.signal = 'saved') as saved,
        COUNT(*) FILTER (WHERE f.signal = 'building') as building,
        COUNT(*) FILTER (WHERE f.signal = 'applied') as applied,
        COUNT(*) FILTER (WHERE f.signal = 'won') as won,
        COUNT(*) FILTER (WHERE f.signal = 'wrong') as wrong
    FROM opportunity_feedback f
    JOIN opportunities o ON f.opportunity_id = o.id
    GROUP BY o.source
    ORDER BY won DESC, applied DESC, building DESC, saved DESC;
    """
    return db_client.fetch_all(query)

def get_outcomes_by_type() -> list[dict[str, Any]]:
    query = """
    SELECT 
        o.opportunity_type,
        COUNT(*) FILTER (WHERE f.signal = 'saved') as saved,
        COUNT(*) FILTER (WHERE f.signal = 'building') as building,
        COUNT(*) FILTER (WHERE f.signal = 'applied') as applied,
        COUNT(*) FILTER (WHERE f.signal = 'won') as won,
        COUNT(*) FILTER (WHERE f.signal = 'wrong') as wrong
    FROM opportunity_feedback f
    JOIN opportunities o ON f.opportunity_id = o.id
    GROUP BY o.opportunity_type
    ORDER BY won DESC, applied DESC, building DESC, saved DESC;
    """
    return db_client.fetch_all(query)

def get_outcomes_by_tag(limit: int = 10) -> list[dict[str, Any]]:
    query = """
    SELECT 
        tag,
        COUNT(*) FILTER (WHERE f.signal = 'saved') as saved,
        COUNT(*) FILTER (WHERE f.signal = 'building') as building,
        COUNT(*) FILTER (WHERE f.signal = 'applied') as applied,
        COUNT(*) FILTER (WHERE f.signal = 'won') as won,
        COUNT(*) FILTER (WHERE f.signal = 'wrong') as wrong
    FROM opportunity_feedback f
    JOIN opportunities o ON f.opportunity_id = o.id
    LEFT JOIN LATERAL UNNEST(o.tags) as tag ON TRUE
    WHERE tag IS NOT NULL
    GROUP BY tag
    ORDER BY won DESC, applied DESC, building DESC, saved DESC
    LIMIT %s;
    """
    return db_client.fetch_all(query, (limit,))

def get_outcomes_by_tech(limit: int = 10) -> list[dict[str, Any]]:
    query = """
    SELECT 
        tech,
        COUNT(*) FILTER (WHERE f.signal = 'saved') as saved,
        COUNT(*) FILTER (WHERE f.signal = 'building') as building,
        COUNT(*) FILTER (WHERE f.signal = 'applied') as applied,
        COUNT(*) FILTER (WHERE f.signal = 'won') as won,
        COUNT(*) FILTER (WHERE f.signal = 'wrong') as wrong
    FROM opportunity_feedback f
    JOIN opportunities o ON f.opportunity_id = o.id
    LEFT JOIN LATERAL UNNEST(o.tech_stack) as tech ON TRUE
    WHERE tech IS NOT NULL
    GROUP BY tech
    ORDER BY won DESC, applied DESC, building DESC, saved DESC
    LIMIT %s;
    """
    return db_client.fetch_all(query, (limit,))

def get_outcomes_by_domain(limit: int = 10) -> list[dict[str, Any]]:
    query = """
    SELECT 
        domain,
        COUNT(*) FILTER (WHERE f.signal = 'saved') as saved,
        COUNT(*) FILTER (WHERE f.signal = 'building') as building,
        COUNT(*) FILTER (WHERE f.signal = 'applied') as applied,
        COUNT(*) FILTER (WHERE f.signal = 'won') as won,
        COUNT(*) FILTER (WHERE f.signal = 'wrong') as wrong
    FROM opportunity_feedback f
    JOIN opportunities o ON f.opportunity_id = o.id
    LEFT JOIN LATERAL UNNEST(o.domains) as domain ON TRUE
    WHERE domain IS NOT NULL
    GROUP BY domain
    ORDER BY won DESC, applied DESC, building DESC, saved DESC
    LIMIT %s;
    """
    return db_client.fetch_all(query, (limit,))

def generate_weekly_report() -> str:
    """Generate markdown-formatted text summarizing all key telemetry metrics."""
    sources = get_outcomes_by_source()
    opp_types = get_outcomes_by_type()
    tags = get_outcomes_by_tag()
    tech = get_outcomes_by_tech()
    domains = get_outcomes_by_domain()
    
    report = []
    report.append("# WEEKLY OUTCOME ANALYTICS REPORT")
    report.append("Generated by: OpportunityOS Analytics Engine\n")
    
    report.append("## Top Ingestion Sources")
    report.append("| Source | Saved | Building | Applied | Won | Wrong |")
    report.append("|--------|-------|----------|---------|-----|-------|")
    for s in sources:
        report.append(f"| {s['source']} | {s['saved']} | {s['building']} | {s['applied']} | {s['won']} | {s['wrong']} |")
    report.append("")
    
    report.append("## Top Opportunity Types")
    report.append("| Type | Saved | Building | Applied | Won | Wrong |")
    report.append("|------|-------|----------|---------|-----|-------|")
    for t in opp_types:
        report.append(f"| {t['opportunity_type']} | {t['saved']} | {t['building']} | {t['applied']} | {t['won']} | {t['wrong']} |")
    report.append("")
    
    report.append("## Top Tags")
    report.append("| Tag | Saved | Building | Applied | Won | Wrong |")
    report.append("|-----|-------|----------|---------|-----|-------|")
    for tg in tags:
        report.append(f"| {tg['tag']} | {tg['saved']} | {tg['building']} | {tg['applied']} | {tg['won']} | {tg['wrong']} |")
    report.append("")
    
    report.append("## Top Tech Stacks")
    report.append("| Tech | Saved | Building | Applied | Won | Wrong |")
    report.append("|------|-------|----------|---------|-----|-------|")
    for tc in tech:
        report.append(f"| {tc['tech']} | {tc['saved']} | {tc['building']} | {tc['applied']} | {tc['won']} | {tc['wrong']} |")
    report.append("")
    
    report.append("## Top Domains")
    report.append("| Domain | Saved | Building | Applied | Won | Wrong |")
    report.append("|--------|-------|----------|---------|-----|-------|")
    for d in domains:
        report.append(f"| {d['domain']} | {d['saved']} | {d['building']} | {d['applied']} | {d['won']} | {d['wrong']} |")
    report.append("")
    
    return "\n".join(report)

def write_weekly_report(filepath: str = "../03_MEMORY/weekly_report.md") -> None:
    """Generate and write weekly_report.md to disk."""
    pool_initialized_here = False
    if not db_client.is_ready():
        db_client.init_pool()
        pool_initialized_here = True
        
    try:
        report_content = generate_weekly_report()
        with open(filepath, "w") as f:
            f.write(report_content)
        logger.info(f"Weekly outcome report generated and written to {filepath}")
    except Exception as e:
        logger.error(f"Failed to generate and write weekly outcome report: {e}")
        raise
    finally:
        if pool_initialized_here:
            db_client.close_pool()
